name: test the challenges

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Running tests
        run: |
          python -m pip install .
          python regex_challenge.py list | xargs -n1 python regex_challenge.py test
