name: test the challenges

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Running tests
        run: |
          python -m pip install poetry
          python -m poetry install
          poetry run python regex_challenge.py list | xargs -n1 poetry run python regex_challenge.py test
