name: test the things

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Running pylint
        uses: fylein/python-pylint-github-action@v4
        with:
          args: |
            python3 -m pip install --no-cache --upgrade pip -r requirements.txt
            python3 -m pylint regex_challenge.py
      - name: Running tests
        run: find ./challenges -type f -exec ./regex_challenge.py test "{}" \;
